#pragma once
namespace T6SDK
{
	enum class DvarSetSource
	{
		DVAR_SOURCE_INTERNAL = 0,
		DVAR_SOURCE_EXTERNAL = 1,
		DVAR_SOURCE_SCRIPT = 2
	};
    enum class EntityType
    {
        GENERALENTITY = 0x00,
		PLAYERENTITY = 0x01,
        PLAYERCORPSEENTITY = 0x02,
        ITEMENTITY = 0x03,
        MISSILEENTITY = 0x04,
        INVISIBLEENTITY = 0x05,
        SCRIPTMOVERENTITY = 0x06,
        SOUNDBLENDENTITY = 0x07,
        FXENTITY = 0x08,
        LOOPFXENTITY = 0x09,
        PRIMARYLIGHTENTITY = 0x0A,
        TURRETENTITY = 0x0B,
        HELICOPTER = 0x0C,
        PLANE = 0x0D,
        VEHICLE = 0x0E,
        VEHICLE_CORPSE = 0x0F,
        ACTOR = 0x10,
        ACTOR_SPAWNER = 0x11,
        ACTOR_CORPSE = 0x12,
        STREAMER_HINT = 0x13,
        ZBARRIER = 0x14,
        TEMPENTITY = 0x15,
        ARCHIVEDENTITY = 0x16,
        MATCHSTATE = 0x17,
        CLIENTSTATE = 0x18,
        PLAYERSTATE = 0x19,
        ACTORSTATE = 0x1A,
        HUDELEM = 0x1B,
        BASELINE = 0x1C,
        GLASS = 0x1D,
        PERF = 0x1E,
        SERVERCMD = 0x1F,
        VOIP_UPLOAD = 0x20,
        VOIP_DOWNLOAD = 0x21,
        DEMO_UPLOAD = 0x22,
        CLIENT_UPLOAD = 0x23,
        CLIENT_PING = 0x24,
        CLIENT_PACKETS = 0x25
    };
    enum class DemoCameraMode
    {
        NONE = 0,
		THIRDPERSON = 1,
        FREECAM = 2
    };
    enum class DemoFreeCameraMode
    {
        FREEROAM = 0,
        EDIT = 1,
        DOLLY = 2
    };
    enum class uiMenuCommand_t
    {
        NONE = 0x0,
        MAIN = 0x1,
        MAINLOBBY = 0x2,
        INGAME = 0x3,
        PREGAME = 0x4,
        POSTGAME = 0x5,
        WM_QUICKMESSAGE = 0x6,
        SCRIPT_POPUP = 0x7,
        SCOREBOARD = 0x8,
        GAMERCARD = 0x9,
        MUTEERROR = 0x0A,
        SPLITSCREENGAMESETUP = 0x0B,
        SYSTEMLINKJOINGAME = 0x0C,
        PARTY = 0x0D,
        WAGER_PARTY = 0x0E,
        LEAGUE_PARTY = 0x0F,
        GAMELOBBY = 0x10,
        WAGERLOBBY = 0x11,
        PRIVATELOBBY = 0x12,
        LEAGUELOBBY = 0x13,
        THEATERLOBBY = 0x14,
        MIGRATION = 0x15,
        CONTROLLERREMOVED = 0x16,
        ENDOFGAME = 0x17
    };
    enum class XAssetType
    {
        XMODELPIECES = 0x0,
        PHYSPRESET = 0x1,
        PHYSCONSTRAINTS = 0x2,
        DESTRUCTIBLEDEF = 0x3,
        XANIMPARTS = 0x4,
        XMODEL = 0x5,
        MATERIAL = 0x6,
        TECHNIQUE_SET = 0x7,
        IMAGE = 0x8,
        SOUND = 0x9,
        SOUND_PATCH = 0x0A,
        CLIPMAP = 0x0B,
        CLIPMAP_PVS = 0x0C,
        COMWORLD = 0x0D,
        GAMEWORLD_SP = 0x0E,
        GAMEWORLD_MP = 0x0F,
        MAP_ENTS = 0x10,
        GFXWORLD = 0x11,
        LIGHT_DEF = 0x12,
        UI_MAP = 0x13,
        FONT = 0x14,
        FONTICON = 0x15,
        MENULIST = 0x16,
        MENU = 0x17,
        LOCALIZE_ENTRY = 0x18,
        WEAPON = 0x19,
        WEAPONDEF = 0x1A,
        WEAPON_VARIANT = 0x1B,
        WEAPON_FULL = 0x1C,
        ATTACHMENT = 0x1D,
        ATTACHMENT_UNIQUE = 0x1E,
        WEAPON_CAMO = 0x1F,
        SNDDRIVER_GLOBALS = 0x20,
        FX = 0x21,
        IMPACT_FX = 0x22,
        AITYPE = 0x23,
        MPTYPE = 0x24,
        MPBODY = 0x25,
        MPHEAD = 0x26,
        CHARACTER = 0x27,
        XMODELALIAS = 0x28,
        RAWFILE = 0x29,
        STRINGTABLE = 0x2A,
        LEADERBOARD = 0x2B,
        XGLOBALS = 0x2C,
        DDL = 0x2D,
        GLASSES = 0x2E,
        EMBLEMSET = 0x2F,
        SCRIPTPARSETREE = 0x30,
        KEYVALUEPAIRS = 0x31,
        VEHICLEDEF = 0x32,
        MEMORYBLOCK = 0x33,
        ADDON_MAP_ENTS = 0x34,
        TRACER = 0x35,
        SKINNEDVERTS = 0x36,
        QDB = 0x37,
        SLUG = 0x38,
        FOOTSTEP_TABLE = 0x39,
        FOOTSTEPFX_TABLE = 0x3A,
        ZBARRIER = 0x3B,
        COUNT = 0x3C,
        STRING = 0x3C,
        ASSETLIST = 0x3D,
        REPORT = 0x3E,
        DEPEND = 0x3F
    };
    enum class eGameModes
    {
        PUBLIC_MATCH = 0,
        PRIVATE_MATCH = 1,
        LOCAL_SPLITSCREEN = 2,
        WAGER_MATCH = 3,
        BASIC_TRAINING = 4,
        THEATER = 5,
        LEAGUE_MATCH = 6,
        RTS = 7,
        MAX = 8,
        INVALID_GAMEMODE = 9
    };
    enum class PlayerTags
    {
        j_mouth_ri = 1173,
        j_mouth_le = 1172,
        j_lip_top_ri = 472,
        j_lip_top_le = 471,
        j_levator_ri = 1161,
        j_levator_le = 1160,
        j_jaw = 470,
        j_head_end = 999,
        j_cheek_le = 1147,
        j_cheek_ri = 1148,
        j_head = 195,
        j_neck = 194,
        j_spine4 = 193,
        j_thumb_ri_3 = 534,
        j_thumb_le_3 = 533,
        j_ring_ri_3 = 532,
        j_ring_le_3 = 531,
        j_pinky_ri_3 = 530,
        j_pinky_le_3 = 529,
        j_mid_ri_3 = 528,
        j_mid_le_3 = 527,
        j_index_ri_3 = 526,
        j_index_le_3 = 525,
        j_thumb_ri_2 = 524,
        j_thumb_le_2 = 523,
        j_ring_ri_2 = 522,
        j_ring_le_2 = 521,
        j_pinky_ri_2 = 520,
        j_pinky_le_2 = 519,
        j_mid_ri_2 = 518,
        j_mid_le_2 = 517,
        j_index_ri_2 = 516,
        j_index_le_2 = 515,
        tag_weapon_right = 212,
        tag_weapon_left = 514,
        j_thumb_ri_1 = 513,
        j_thumb_le_1 = 512,
        j_ring_ri_1 = 511,
        j_ring_le_1 = 510,
        j_pinky_ri_1 = 509,
        j_pinky_le_1 = 508,
        j_mid_ri_1 = 507,
        j_mid_le_1 = 506,
        j_index_ri_1 = 505,
        j_index_le_1 = 504,
        j_wristtwist_ri = 205,
        j_wristtwist_le = 200,
        j_wrist_ri = 204,
        j_wrist_le = 199,
        j_shouldertwist_ri = 502,
        j_shouldertwist_le = 501,
        j_elbow_ri = 203,
        j_elbow_le = 198,
        j_elbow_bulge_ri = 500,
        j_elbow_bulge_le = 499,
        j_shoulder_ri = 202,
        j_shoulder_le = 197,
        j_clavicle_ri = 201,
        j_clavicle_le = 196,
        j_ball_ri = 460,
        j_ball_le = 459,
        j_ankle_ri = 211,
        j_ankle_le = 208,
        back_mid = 3029,
        j_knee_ri = 210,
        j_knee_le = 207,
        back_low = 3028,
        j_chin_skinroll = 1151,
        torso_stabilizer = 1128,
        j_hip_ri = 209,
        j_hip_le = 206,
        pelvis = 3027,
        j_mainroot = 190,
        tag_origin = 189
    };
    enum class GfxDrawSceneMethod
    {
        GFX_DRAW_SCENE_NONE,
        GFX_DRAW_SCENE_FULLBRIGHT,
        GFX_DRAW_SCENE_DEBUGSHADER,
        GFX_DRAW_SCENE_STANDARD
    };
    enum class EventType
    {
        OnGameLoaded,
        OnGameModeChanged,
        OnTheaterControlsDrawn,
        OnActiveFrameDrawn,
        OnViewMatrixWritten,
        OnEndFrameDrawn,
        OnTickChanged,
        OnAspectRatioChanged,
        OnCameraMarkerAdded,
        OnFreeCameraModeChanged,
        OnCameraModeChanged,
        OnKeyPressed,
        OnMouseLeftButtonClicked,
		OnMouseRightButtonClicked,
        OnMouseWheelUp,
		OnMouseWheelDown,
        OnSafeStringTranslated,
        OnPovCamoWriting,
        OnAxisToAngles,
        OnDemoPlaybackInited,
        OnSunInited
    };
    enum class AnchorPoint
    {
        TopLeft = 0,
        TopCenter = 1,
        TopRight = 2,
        CenterLeft = 3,
        Center = 4,
        CenterRight = 5,
        BottomLeft = 6,
        BottomCenter = 7,
        BottomRight = 8
    };
}